# Generated by Django 4.2.7 on 2024-04-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_custom_password_userprofile_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcredito',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
