# Generated by Django 4.2.7 on 2024-04-23 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_alter_microcredito_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcredito',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='microcredito',
            name='init_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='microcredito',
            name='trade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microcredito',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
